module.exports = {
  collectCoverage: false,
  collectCoverageFrom: [
    "src/**/*",
    "!src/**/index.ts",
    "!src/**/*.styled.ts",
    "!src/**/*.styled.tsx",
    "!node_modules/",
    "!src/__tests__/**",
    "!src/services/**",
    "!src/routes/**",
    "!src/database/",
    "!src/contexts/**",
    "!src/mock/**",
    "!src/utils/",
    "!src/screens/app/Home/**",
    "!src/screens/app/Roadmap/**",
    "!src/screens/app/Maps/**",
    "!src/screens/app/Favorite/**",
    "!src/screens/auth/SignUp/**",
    "!src/screens/auth/SignIn/**",
    "!src/screens/auth/ForgotPassword/**",

    "!src/@types/*",
  ],
  testPathIgnorePatterns: [
    ".mock.js",
    ".mock.ts",
    "/node_modules/(?!my-package)(.*)",
  ],
  resetMocks: false,
  setupFiles: ["./src/utils/reactNativeLibrariesJestMock.js"],
  preset: "react-native",
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  modulePathIgnorePatterns: [".mock.js", ".mock.ts"],
  moduleNameMapper: {
    ".+\\.(png|jpg|ttf|woff|woff2)$": "jest-transform-stub",
  },
};
