version: '3'

services:
  frontend:
    image: frontend
    build: ./travel-friends-web
    ports:
      - 3000:3000
    depends_on:
      - node
    volumes:
      - ./travel-friends-web:/app/
      - /app/node_modules
  node:
    image: api
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/app/
      - /app/node_modules
