version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    working_directory: ~/travel-friends/travel-friends-web
    executor: node/default
    steps:
      - checkout:
          path: ~/travel-friends
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
